[phases.setup]
nixPkgs = ["nodejs_22", "vips"]

[phases.install]
cmds = ["corepack enable pnpm && corepack prepare pnpm@latest --activate && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"
