/**
 * Comprehensive global tattoo style taxonomy for tatt-ooo.
 * Based on full research + ChatGPT taxonomy planning session.
 */

export interface TattooStyle {
  id: string;
  name: string;
  category: TattooCategory;
  description: string;
  visualTraits: string[];
  commonMotifs: string[];
  promptKeywords: string;
  difficulty: "easy" | "medium" | "advanced";
  popularity: number; // 1-10
  colorMode: "black" | "black-grey" | "full-color" | "black-grey/full-color";
  placementFit: string[];
  tool: string;
  toolEmoji: string;
  origin: string;
  culturalSensitive?: boolean;
  featured?: boolean;
}

export type TattooCategory =
  | "Classic"
  | "Minimal & Modern"
  | "Artistic & Detailed"
  | "Dark & Graphic"
  | "Futuristic & Conceptual"
  | "Cultural & Sacred"
  | "Hand-Poke & Traditional"
  | "Underground & Street";

export const TATTOO_CATEGORIES: TattooCategory[] = [
  "Classic",
  "Minimal & Modern",
  "Artistic & Detailed",
  "Dark & Graphic",
  "Futuristic & Conceptual",
  "Cultural & Sacred",
  "Hand-Poke & Traditional",
  "Underground & Street",
];

export const TATTOO_STYLES: TattooStyle[] = [
  // ── CLASSIC ──────────────────────────────────────────────────────────────
  {
    id: "american_traditional",
    name: "American Traditional",
    category: "Classic",
    description: "Bold black outlines, flat colour fills, iconic imagery. Pioneered by Sailor Jerry. The foundation of modern Western tattooing.",
    visualTraits: ["bold outlines", "flat colour fills", "limited palette", "iconic imagery"],
    commonMotifs: ["eagles", "anchors", "roses", "daggers", "swallows", "pin-ups", "panthers"],
    promptKeywords: "traditional American tattoo, bold black outlines, flat color fills, sailor jerry style, old school tattoo, limited color palette",
    difficulty: "medium",
    popularity: 9,
    colorMode: "full-color",
    placementFit: ["arm", "chest", "calf", "thigh", "shoulder"],
    tool: "Coil Tattoo Machine",
    toolEmoji: "🔫",
    origin: "United States",
    featured: true,
  },
  {
    id: "neo_traditional",
    name: "Neo-Traditional",
    category: "Classic",
    description: "Evolution of traditional — richer colours, more detail, Art Nouveau influences, decorative elements and depth.",
    visualTraits: ["rich colour palette", "Art Nouveau influence", "decorative borders", "strong outlines"],
    commonMotifs: ["animals", "portraits", "flowers", "mythical creatures", "nature"],
    promptKeywords: "neo-traditional tattoo, rich colors, art nouveau influence, decorative elements, strong outlines, detailed shading, ornate borders",
    difficulty: "advanced",
    popularity: 9,
    colorMode: "full-color",
    placementFit: ["arm", "thigh", "back", "chest"],
    tool: "Rotary / Coil Machine",
    toolEmoji: "🔫",
    origin: "United States / Europe",
    featured: true,
  },
  {
    id: "japanese_irezumi",
    name: "Japanese / Irezumi",
    category: "Classic",
    description: "Full traditional Japanese tattooing — koi fish, dragons, tigers, cherry blossoms, waves. Bold outlines, rich colours, full body coverage.",
    visualTraits: ["dynamic", "layered", "bold", "ornamental", "flowing composition"],
    commonMotifs: ["dragons", "koi fish", "tigers", "waves", "peonies", "hannya masks", "cherry blossoms"],
    promptKeywords: "traditional Japanese irezumi tattoo, bold outlines, rich colors, koi fish, dragons, cherry blossoms, waves, Japanese woodblock print style",
    difficulty: "advanced",
    popularity: 10,
    colorMode: "black-grey/full-color",
    placementFit: ["sleeve", "back", "chest", "leg"],
    tool: "Tebori or Rotary Machine",
    toolEmoji: "⛩️",
    origin: "Japan",
    featured: true,
  },
  {
    id: "chicano",
    name: "Chicano",
    category: "Classic",
    description: "Born in Chicano culture — fine black and grey linework, religious iconography, portraits, lettering and roses.",
    visualTraits: ["black & grey", "religious imagery", "fine linework", "portrait work"],
    commonMotifs: ["Virgin Mary", "roses", "portraits", "lowriders", "script lettering", "clowns"],
    promptKeywords: "chicano tattoo style, black and grey, fine linework, religious iconography, detailed portraits, roses and lettering",
    difficulty: "advanced",
    popularity: 8,
    colorMode: "black-grey",
    placementFit: ["chest", "back", "arm", "neck"],
    tool: "Coil Machine",
    toolEmoji: "🔫",
    origin: "Mexico / USA",
    featured: true,
  },
  {
    id: "tribal",
    name: "Tribal",
    category: "Classic",
    description: "Bold black patterns inspired by indigenous traditions worldwide. Strong geometric forms, solid fills, cultural symbolism.",
    visualTraits: ["bold black", "geometric forms", "solid fills", "symmetrical"],
    commonMotifs: ["bands", "spirals", "abstract shapes", "animal forms"],
    promptKeywords: "tribal tattoo, bold black geometric patterns, solid fills, symmetrical tribal design, indigenous inspired",
    difficulty: "medium",
    popularity: 7,
    colorMode: "black",
    placementFit: ["arm", "shoulder", "back", "calf"],
    tool: "Coil Machine",
    toolEmoji: "🔫",
    origin: "Global",
  },
  {
    id: "celtic",
    name: "Celtic / Norse",
    category: "Classic",
    description: "Intricate knotwork, interlacing patterns, Celtic crosses, runes and Norse mythology. Continuous interlocking lines.",
    visualTraits: ["knotwork", "interlacing", "Celtic crosses", "Norse runes"],
    commonMotifs: ["knotwork", "Celtic cross", "Mjolnir", "Valknut", "runes", "Yggdrasil"],
    promptKeywords: "Celtic tattoo style, intricate knotwork, interlacing patterns, Celtic cross, Norse runes, Viking symbols, continuous interlocking lines",
    difficulty: "advanced",
    popularity: 7,
    colorMode: "black",
    placementFit: ["arm", "back", "chest", "calf"],
    tool: "Coil / Rotary Machine",
    toolEmoji: "☘️",
    origin: "Ireland / Scotland / Scandinavia",
  },
  {
    id: "nordic_viking",
    name: "Nordic / Viking",
    category: "Classic",
    description: "Norse mythology, Viking symbols, runes and Scandinavian art. Rugged, powerful imagery with deep ancestral meaning.",
    visualTraits: ["runic symbols", "Norse imagery", "bold lines", "mythological"],
    commonMotifs: ["Odin", "ravens", "wolves", "Valknut", "compass", "longships"],
    promptKeywords: "Viking Norse tattoo, runic symbols, Norse mythology, Odin ravens wolves, Valknut, Nordic art style, bold lines",
    difficulty: "medium",
    popularity: 8,
    colorMode: "black-grey",
    placementFit: ["arm", "chest", "back", "shoulder"],
    tool: "Coil Machine",
    toolEmoji: "⚔️",
    origin: "Scandinavia",
  },

  // ── MINIMAL & MODERN ─────────────────────────────────────────────────────
  {
    id: "fine_line",
    name: "Fine Line",
    category: "Minimal & Modern",
    description: "Delicate, precise linework using a single needle. Minimal shading, elegant and understated. Perfect for subtle placements.",
    visualTraits: ["delicate lines", "single needle", "minimal shading", "elegant detail"],
    commonMotifs: ["flowers", "names", "symbols", "celestial", "butterflies", "animals"],
    promptKeywords: "fine line tattoo style, single needle, delicate thin lines, minimal shading, elegant, precise linework, understated beauty",
    difficulty: "advanced",
    popularity: 10,
    colorMode: "black",
    placementFit: ["wrist", "forearm", "ribs", "ankle", "collarbone", "fingers"],
    tool: "Single-Needle Machine",
    toolEmoji: "🔫",
    origin: "Los Angeles, USA",
    featured: true,
  },
  {
    id: "minimalist",
    name: "Minimalist",
    category: "Minimal & Modern",
    description: "Less is more — simple shapes, clean lines, maximum impact with minimum ink. Timeless and versatile.",
    visualTraits: ["simple shapes", "clean lines", "negative space", "minimal detail"],
    commonMotifs: ["geometric shapes", "symbols", "words", "simple animals", "celestial"],
    promptKeywords: "minimalist tattoo, simple clean lines, negative space, minimal detail, elegant simplicity, small tattoo design",
    difficulty: "easy",
    popularity: 10,
    colorMode: "black",
    placementFit: ["wrist", "ankle", "behind ear", "finger", "collarbone"],
    tool: "Single-Needle Machine",
    toolEmoji: "🔫",
    origin: "Global",
    featured: true,
  },
  {
    id: "micro",
    name: "Micro Tattoo",
    category: "Minimal & Modern",
    description: "Tiny, intricate tattoos — incredibly detailed work at a very small scale. Requires exceptional precision.",
    visualTraits: ["tiny scale", "high detail", "precise", "delicate"],
    commonMotifs: ["portraits", "animals", "flowers", "symbols", "landscapes"],
    promptKeywords: "micro tattoo, tiny intricate design, small scale high detail, miniature tattoo art, precise fine detail",
    difficulty: "advanced",
    popularity: 8,
    colorMode: "black-grey",
    placementFit: ["finger", "wrist", "behind ear", "ankle", "inner arm"],
    tool: "Single-Needle Machine",
    toolEmoji: "🔫",
    origin: "Global",
  },
  {
    id: "geometric",
    name: "Geometric",
    category: "Minimal & Modern",
    description: "Precise geometric shapes, sacred geometry, mandalas and patterns. Mathematical precision meets body art.",
    visualTraits: ["geometric shapes", "sacred geometry", "mandalas", "mathematical precision"],
    commonMotifs: ["mandalas", "sacred geometry", "animals in geometry", "patterns", "crystals"],
    promptKeywords: "geometric tattoo style, precise geometric shapes, sacred geometry, mandala patterns, symmetrical, mathematical precision, dotwork shading",
    difficulty: "advanced",
    popularity: 9,
    colorMode: "black",
    placementFit: ["forearm", "chest", "back", "thigh", "shoulder"],
    tool: "Rotary Machine",
    toolEmoji: "🔫",
    origin: "Global",
    featured: true,
  },
  {
    id: "dotwork",
    name: "Dotwork / Stippling",
    category: "Minimal & Modern",
    description: "Images built entirely from dots — creates texture, shading and form through stippling technique.",
    visualTraits: ["dot-based shading", "stippling technique", "textured appearance"],
    commonMotifs: ["mandalas", "geometric", "animals", "portraits", "nature"],
    promptKeywords: "dotwork tattoo style, stippling technique, dot-based shading, textured appearance, intricate dot patterns, mandala dotwork",
    difficulty: "advanced",
    popularity: 8,
    colorMode: "black",
    placementFit: ["forearm", "chest", "back", "shoulder"],
    tool: "Single-Needle Machine",
    toolEmoji: "🔫",
    origin: "Global",
  },
  {
    id: "ornamental",
    name: "Ornamental",
    category: "Minimal & Modern",
    description: "Decorative jewellery-inspired designs — intricate patterns, filigree, lace, and ornate details that adorn the body.",
    visualTraits: ["jewellery-like", "filigree", "lace patterns", "ornate detail"],
    commonMotifs: ["filigree", "lace", "jewels", "chains", "crowns", "flowers"],
    promptKeywords: "ornamental tattoo style, jewellery inspired, filigree patterns, lace detail, ornate decorative, elegant body adornment",
    difficulty: "advanced",
    popularity: 8,
    colorMode: "black",
    placementFit: ["collarbone", "spine", "hands", "feet", "forearm"],
    tool: "Single-Needle Machine",
    toolEmoji: "🔫",
    origin: "Global",
    featured: true,
  },
  {
    id: "linework",
    name: "Linework",
    category: "Minimal & Modern",
    description: "Pure line-based art — no shading, just clean confident lines. Architectural, precise, and bold.",
    visualTraits: ["clean lines", "no shading", "architectural", "bold strokes"],
    commonMotifs: ["architecture", "animals", "portraits", "abstract shapes"],
    promptKeywords: "linework tattoo, clean precise lines, no shading, line art tattoo, architectural line drawing, bold confident strokes",
    difficulty: "medium",
    popularity: 7,
    colorMode: "black",
    placementFit: ["forearm", "calf", "ribs", "back"],
    tool: "Rotary Machine",
    toolEmoji: "🔫",
    origin: "Global",
  },
  {
    id: "sticker_style",
    name: "Sticker Style",
    category: "Minimal & Modern",
    description: "Looks like a sticker on skin — bold outlines, flat fills, clean and graphic. Fun and contemporary.",
    visualTraits: ["sticker-like", "bold outline", "flat fills", "graphic"],
    commonMotifs: ["animals", "characters", "logos", "symbols", "food"],
    promptKeywords: "sticker style tattoo, bold outline, flat color fills, graphic sticker aesthetic, clean contemporary tattoo",
    difficulty: "easy",
    popularity: 7,
    colorMode: "full-color",
    placementFit: ["arm", "calf", "ankle", "shoulder"],
    tool: "Rotary Machine",
    toolEmoji: "🔫",
    origin: "Global",
  },

  // ── ARTISTIC & DETAILED ───────────────────────────────────────────────────
  {
    id: "black_grey_realism",
    name: "Black & Grey Realism",
    category: "Artistic & Detailed",
    description: "Photorealistic imagery using only black and grey inks. Originated in LA prison culture, now one of the most respected styles.",
    visualTraits: ["photorealistic", "black & grey only", "fine shading", "smooth gradients"],
    commonMotifs: ["portraits", "animals", "landscapes", "religious", "memorial"],
    promptKeywords: "black and grey realism tattoo, photorealistic, smooth gradients, fine shading, monochromatic, highly detailed, realistic portrait tattoo",
    difficulty: "advanced",
    popularity: 10,
    colorMode: "black-grey",
    placementFit: ["arm", "back", "chest", "thigh", "calf"],
    tool: "Rotary Machine + Fine Needles",
    toolEmoji: "🔫",
    origin: "Los Angeles, USA",
    featured: true,
  },
  {
    id: "colour_realism",
    name: "Colour Realism",
    category: "Artistic & Detailed",
    description: "Full-colour photorealistic tattoos. Requires exceptional skill in colour theory and blending.",
    visualTraits: ["full colour", "photorealistic", "complex shading", "vivid pigments"],
    commonMotifs: ["portraits", "animals", "flowers", "landscapes", "pop culture"],
    promptKeywords: "color realism tattoo, full color photorealistic, vivid pigments, complex color shading, lifelike detail, realistic tattoo art",
    difficulty: "advanced",
    popularity: 9,
    colorMode: "full-color",
    placementFit: ["arm", "back", "thigh", "calf"],
    tool: "Rotary Machine + Fine Needles",
    toolEmoji: "🔫",
    origin: "Global",
    featured: true,
  },
  {
    id: "illustrative",
    name: "Illustrative",
    category: "Artistic & Detailed",
    description: "Looks like ink illustration or engraving — combines linework with shading, like a drawing come to life.",
    visualTraits: ["illustration style", "linework + shading", "engraving feel", "artistic"],
    commonMotifs: ["animals", "portraits", "nature", "mythology", "architecture"],
    promptKeywords: "illustrative tattoo style, ink illustration, engraving style, detailed linework with shading, artistic drawing tattoo",
    difficulty: "medium",
    popularity: 9,
    colorMode: "black-grey",
    placementFit: ["arm", "thigh", "back", "chest"],
    tool: "Rotary Machine",
    toolEmoji: "🔫",
    origin: "Global",
    featured: true,
  },
  {
    id: "sketch_etching",
    name: "Sketch / Etching",
    category: "Artistic & Detailed",
    description: "Looks like a pencil sketch or copper plate etching — rough, expressive lines with cross-hatching and texture.",
    visualTraits: ["sketch lines", "cross-hatching", "rough texture", "expressive"],
    commonMotifs: ["portraits", "animals", "architecture", "nature"],
    promptKeywords: "sketch style tattoo, pencil sketch aesthetic, cross-hatching, etching style, rough expressive lines, artistic sketch tattoo",
    difficulty: "advanced",
    popularity: 7,
    colorMode: "black-grey",
    placementFit: ["arm", "thigh", "back"],
    tool: "Rotary Machine",
    toolEmoji: "🔫",
    origin: "Global",
  },
  {
    id: "surrealism",
    name: "Surrealism",
    category: "Artistic & Detailed",
    description: "Dream-like, impossible imagery inspired by Salvador Dali. Reality bending, melting forms, unexpected juxtapositions.",
    visualTraits: ["dream-like", "impossible imagery", "reality bending", "Dali-inspired"],
    commonMotifs: ["melting clocks", "eyes", "dreamscapes", "impossible objects", "hybrid creatures"],
    promptKeywords: "surrealist tattoo style, Salvador Dali inspired, dream-like impossible imagery, melting forms, reality bending, unexpected juxtapositions",
    difficulty: "advanced",
    popularity: 7,
    colorMode: "black-grey/full-color",
    placementFit: ["arm", "back", "thigh"],
    tool: "Rotary Machine",
    toolEmoji: "🎨",
    origin: "Global",
  },
  {
    id: "watercolour",
    name: "Watercolour",
    category: "Artistic & Detailed",
    description: "Mimics watercolour painting — soft colour washes, bleeding edges, painterly strokes without hard outlines.",
    visualTraits: ["soft colour washes", "no hard outlines", "painterly style", "bleeding edges"],
    commonMotifs: ["flowers", "animals", "landscapes", "abstract", "portraits"],
    promptKeywords: "watercolor tattoo style, soft color washes, painterly brushstrokes, bleeding edges, no hard outlines, fluid color transitions, artistic",
    difficulty: "advanced",
    popularity: 8,
    colorMode: "full-color",
    placementFit: ["arm", "back", "ribs", "thigh"],
    tool: "Rotary Machine",
    toolEmoji: "🎨",
    origin: "Global",
    featured: true,
  },
  {
    id: "abstract",
    name: "Abstract",
    category: "Artistic & Detailed",
    description: "Non-representational art — shapes, colours and forms that evoke emotion rather than depicting reality.",
    visualTraits: ["non-representational", "expressive", "colour-driven", "emotional"],
    commonMotifs: ["shapes", "splashes", "lines", "colour fields", "textures"],
    promptKeywords: "abstract tattoo style, non-representational art, expressive shapes and colors, emotional abstract design, contemporary art tattoo",
    difficulty: "advanced",
    popularity: 6,
    colorMode: "full-color",
    placementFit: ["arm", "back", "thigh"],
    tool: "Rotary Machine",
    toolEmoji: "🎨",
    origin: "Global",
  },

  // ── DARK & GRAPHIC ────────────────────────────────────────────────────────
  {
    id: "blackwork",
    name: "Blackwork",
    category: "Dark & Graphic",
    description: "Pure black ink only — bold geometric patterns, tribal-inspired designs, and high-contrast illustrative work.",
    visualTraits: ["black ink only", "high contrast", "geometric patterns", "negative space"],
    commonMotifs: ["snakes", "masks", "demons", "abstract shapes", "tribal-inspired"],
    promptKeywords: "blackwork tattoo style, pure black ink, bold geometric patterns, high contrast, negative space, illustrative blackwork",
    difficulty: "medium",
    popularity: 9,
    colorMode: "black",
    placementFit: ["arm", "calf", "thigh", "chest", "back"],
    tool: "Rotary Machine",
    toolEmoji: "🔫",
    origin: "Global",
    featured: true,
  },
  {
    id: "dark_art_gothic",
    name: "Dark Art / Gothic",
    category: "Dark & Graphic",
    description: "Dark, macabre imagery — skulls, demons, death, horror elements. Gothic architecture, Victorian mourning aesthetics.",
    visualTraits: ["dark", "macabre", "gothic", "detailed shadows"],
    commonMotifs: ["skulls", "demons", "ravens", "gothic architecture", "roses with thorns", "hourglasses"],
    promptKeywords: "dark art gothic tattoo, macabre imagery, skulls demons, gothic aesthetic, Victorian mourning, dark detailed shading, horror art tattoo",
    difficulty: "advanced",
    popularity: 8,
    colorMode: "black-grey",
    placementFit: ["arm", "back", "chest", "thigh"],
    tool: "Coil Machine",
    toolEmoji: "💀",
    origin: "Global",
  },
  {
    id: "trash_polka",
    name: "Trash Polka",
    category: "Dark & Graphic",
    description: "German style combining realism with abstract elements — black and red only, chaotic yet deliberate compositions.",
    visualTraits: ["black & red only", "realism + abstract", "chaotic composition", "bold contrast"],
    commonMotifs: ["clocks", "animals", "geometric chaos", "text", "realistic elements"],
    promptKeywords: "trash polka tattoo style, black and red only, realistic elements with abstract chaos, bold contrast, German tattoo art, dynamic composition",
    difficulty: "advanced",
    popularity: 6,
    colorMode: "black-grey",
    placementFit: ["arm", "back", "thigh", "chest"],
    tool: "Coil Machine",
    toolEmoji: "🔫",
    origin: "Germany",
  },
  {
    id: "ignorant_style",
    name: "Ignorant Style",
    category: "Dark & Graphic",
    description: "Deliberately naive, childlike drawings — looks like doodles or sketches. Anti-establishment, humorous, intentionally rough.",
    visualTraits: ["childlike", "naive drawing", "doodle aesthetic", "humorous"],
    commonMotifs: ["cartoon characters", "simple animals", "random objects", "faces", "words"],
    promptKeywords: "ignorant style tattoo, deliberately naive childlike drawing, doodle aesthetic, rough sketch lines, anti-establishment humor, simple cartoon",
    difficulty: "easy",
    popularity: 6,
    colorMode: "black",
    placementFit: ["arm", "leg", "hand", "foot"],
    tool: "Coil Machine",
    toolEmoji: "✏️",
    origin: "France / Global Underground",
  },
  {
    id: "cyber_sigilism",
    name: "Cyber Sigilism",
    category: "Dark & Graphic",
    description: "Sharp, spiked, futuristic symbolic linework. Angular, alien, spiky cyber aesthetic with occult undertones.",
    visualTraits: ["angular", "alien", "spiky", "cyber", "sleek"],
    commonMotifs: ["sigils", "blades", "abstract symbols", "chrome-like forms"],
    promptKeywords: "cyber sigilism tattoo, futuristic sigils, sharp black linework, techno occult aesthetic, angular spiky design, alien symbols",
    difficulty: "advanced",
    popularity: 8,
    colorMode: "black",
    placementFit: ["neck", "forearm", "spine", "shoulder", "chest"],
    tool: "Single-Needle Machine",
    toolEmoji: "⚡",
    origin: "Global / Internet Culture",
    featured: true,
  },

  // ── FUTURISTIC & CONCEPTUAL ───────────────────────────────────────────────
  {
    id: "biomechanical",
    name: "Biomechanical",
    category: "Futuristic & Conceptual",
    description: "Inspired by H.R. Giger — mechanical parts fused with organic tissue. Looks like machinery beneath the skin.",
    visualTraits: ["mechanical + organic", "3D illusion", "Giger-inspired", "complex shading"],
    commonMotifs: ["gears", "pistons", "circuits", "bones", "tendons", "alien machinery"],
    promptKeywords: "biomechanical tattoo style, HR Giger inspired, mechanical parts fused with organic tissue, 3D illusion, machinery beneath skin, detailed shading",
    difficulty: "advanced",
    popularity: 7,
    colorMode: "black-grey",
    placementFit: ["arm", "calf", "back", "shoulder"],
    tool: "Coil / Rotary Machine",
    toolEmoji: "⚙️",
    origin: "Switzerland / USA",
  },
  {
    id: "bio_organic",
    name: "Bio-Organic",
    category: "Futuristic & Conceptual",
    description: "Alien organic forms — flowing, tentacle-like shapes, bioluminescent aesthetics, otherworldly creatures.",
    visualTraits: ["alien organic", "flowing forms", "bioluminescent", "otherworldly"],
    commonMotifs: ["tentacles", "alien creatures", "organic shapes", "flowing forms"],
    promptKeywords: "bio-organic tattoo style, alien organic forms, flowing tentacle shapes, bioluminescent aesthetic, otherworldly creature design",
    difficulty: "advanced",
    popularity: 6,
    colorMode: "black-grey/full-color",
    placementFit: ["arm", "back", "thigh"],
    tool: "Rotary Machine",
    toolEmoji: "👾",
    origin: "Global",
  },
  {
    id: "futuristic_tribal",
    name: "Futuristic Tribal",
    category: "Futuristic & Conceptual",
    description: "Tribal patterns reimagined with a sci-fi twist — geometric tribal forms with technological elements.",
    visualTraits: ["geometric tribal", "sci-fi elements", "bold black", "angular"],
    commonMotifs: ["tribal patterns", "circuit-like forms", "angular shapes"],
    promptKeywords: "futuristic tribal tattoo, sci-fi tribal patterns, geometric tribal with technology elements, bold black angular design",
    difficulty: "medium",
    popularity: 7,
    colorMode: "black",
    placementFit: ["arm", "shoulder", "back", "calf"],
    tool: "Coil Machine",
    toolEmoji: "🚀",
    origin: "Global",
  },
  {
    id: "techno_ornamental",
    name: "Techno Ornamental",
    category: "Futuristic & Conceptual",
    description: "Ornamental patterns fused with circuit boards, data streams and technological motifs.",
    visualTraits: ["circuit patterns", "ornamental tech", "precise lines", "futuristic"],
    commonMotifs: ["circuit boards", "data streams", "geometric tech", "ornamental patterns"],
    promptKeywords: "techno ornamental tattoo, circuit board patterns, ornamental technology design, futuristic decorative tattoo, precise technical linework",
    difficulty: "advanced",
    popularity: 6,
    colorMode: "black",
    placementFit: ["forearm", "spine", "chest", "shoulder"],
    tool: "Single-Needle Machine",
    toolEmoji: "💻",
    origin: "Global",
  },

  // ── CULTURAL & SACRED ─────────────────────────────────────────────────────
  {
    id: "polynesian",
    name: "Polynesian / Maori",
    category: "Cultural & Sacred",
    description: "Bold geometric patterns with deep cultural meaning. Maori Ta Moko uses curved lines representing ancestry.",
    visualTraits: ["bold geometry", "cultural meaning", "curved patterns", "full coverage"],
    commonMotifs: ["koru spirals", "fish hooks", "turtles", "waves", "tribal bands"],
    promptKeywords: "Polynesian tattoo style, Maori ta moko inspired, bold geometric patterns, tribal curves, Pacific Islander tattoo art, koru spirals",
    difficulty: "advanced",
    popularity: 8,
    colorMode: "black",
    placementFit: ["arm", "shoulder", "back", "calf", "chest"],
    tool: "Bone Comb (Traditional) / Machine",
    toolEmoji: "🦴",
    origin: "Polynesia / New Zealand",
    culturalSensitive: true,
    featured: true,
  },
  {
    id: "samoan",
    name: "Samoan Pe'a",
    category: "Cultural & Sacred",
    description: "Traditional Samoan tattooing using a bone comb. The Pe'a covers from waist to knees. Deeply sacred and ceremonial.",
    visualTraits: ["bone comb tool", "full coverage", "sacred ceremony", "geometric patterns"],
    commonMotifs: ["Samoan geometric patterns", "ancestral symbols", "full body coverage"],
    promptKeywords: "Samoan pe'a inspired tattoo style, traditional geometric Samoan patterns, sacred tribal tattoo, Pacific traditional art, full coverage design",
    difficulty: "advanced",
    popularity: 5,
    colorMode: "black",
    placementFit: ["full body", "thigh", "back"],
    tool: "Bone Comb (Au)",
    toolEmoji: "🦴",
    origin: "Samoa",
    culturalSensitive: true,
  },
  {
    id: "sak_yant",
    name: "Sak Yant (Bamboo)",
    category: "Cultural & Sacred",
    description: "Sacred Thai tattoos applied by Buddhist monks using a long bamboo stick. Geometric patterns with Pali script, believed to offer protection.",
    visualTraits: ["sacred geometry", "Pali script", "spiritual meaning", "bamboo tool"],
    commonMotifs: ["yantra symbols", "Pali script", "tigers", "geometric patterns", "Buddhist imagery"],
    promptKeywords: "sak yant Thai bamboo tattoo inspired, sacred geometry, Pali script, Buddhist spiritual tattoo, geometric patterns, yantra symbols",
    difficulty: "advanced",
    popularity: 6,
    colorMode: "black",
    placementFit: ["back", "shoulder", "chest", "arm"],
    tool: "Bamboo Stick with Needle",
    toolEmoji: "🎋",
    origin: "Thailand / Southeast Asia",
    culturalSensitive: true,
  },
  {
    id: "mandala",
    name: "Mandala",
    category: "Cultural & Sacred",
    description: "Circular spiritual symbols from Hindu and Buddhist traditions. Perfect symmetry, intricate geometric patterns radiating from centre.",
    visualTraits: ["perfect symmetry", "circular patterns", "spiritual meaning", "intricate detail"],
    commonMotifs: ["lotus", "geometric patterns", "concentric circles", "sacred symbols"],
    promptKeywords: "mandala tattoo style, perfect circular symmetry, intricate geometric patterns, spiritual Hindu Buddhist art, radiating from center, dotwork shading",
    difficulty: "advanced",
    popularity: 9,
    colorMode: "black",
    placementFit: ["back", "chest", "thigh", "shoulder"],
    tool: "Rotary Machine",
    toolEmoji: "🕉️",
    origin: "India / Tibet",
    featured: true,
  },
  {
    id: "henna_inspired",
    name: "Mehndi / Henna-Inspired",
    category: "Cultural & Sacred",
    description: "Permanent tattoo inspired by henna mehndi patterns — flowing floral vines, paisley, geometric lace-like patterns.",
    visualTraits: ["floral vines", "paisley patterns", "lace-like", "flowing lines"],
    commonMotifs: ["floral vines", "paisley", "geometric lace", "hands", "feet patterns"],
    promptKeywords: "mehndi henna-inspired tattoo style, flowing floral vines, paisley patterns, lace-like geometric designs, Indian bridal art, intricate fine line",
    difficulty: "advanced",
    popularity: 7,
    colorMode: "black",
    placementFit: ["hands", "feet", "forearm", "collarbone"],
    tool: "Single-Needle Machine",
    toolEmoji: "🌿",
    origin: "India / Middle East / North Africa",
    culturalSensitive: true,
  },
  {
    id: "aztec_mayan",
    name: "Aztec / Mayan",
    category: "Cultural & Sacred",
    description: "Pre-Columbian imagery — sun stones, feathered serpents, warriors, geometric calendar patterns and Aztec gods.",
    visualTraits: ["sun stone", "feathered serpent", "warrior imagery", "calendar patterns"],
    commonMotifs: ["sun stone", "Quetzalcoatl", "Aztec warrior", "calendar", "eagle warrior"],
    promptKeywords: "Aztec Mayan tattoo style, pre-Columbian imagery, sun stone, feathered serpent Quetzalcoatl, Aztec warrior, geometric calendar patterns",
    difficulty: "advanced",
    popularity: 7,
    colorMode: "black-grey",
    placementFit: ["arm", "chest", "back", "calf"],
    tool: "Coil Machine",
    toolEmoji: "🏛️",
    origin: "Mexico / Central America",
    culturalSensitive: true,
  },
  {
    id: "haida",
    name: "Haida / Pacific Northwest",
    category: "Cultural & Sacred",
    description: "Indigenous Pacific Northwest art — formline design, ovoid shapes, ravens, eagles, orcas and bears.",
    visualTraits: ["formline design", "ovoid shapes", "animal totems", "bold black"],
    commonMotifs: ["raven", "eagle", "orca", "bear", "salmon", "totem animals"],
    promptKeywords: "Haida Pacific Northwest tattoo style, formline design, ovoid shapes, raven eagle orca totem animals, indigenous Canadian art, bold black",
    difficulty: "advanced",
    popularity: 5,
    colorMode: "black",
    placementFit: ["arm", "shoulder", "back", "chest"],
    tool: "Coil Machine",
    toolEmoji: "🦅",
    origin: "Canada / Pacific Northwest",
    culturalSensitive: true,
  },
  {
    id: "aboriginal",
    name: "Aboriginal / Indigenous",
    category: "Cultural & Sacred",
    description: "Dot painting aesthetics translated to tattoo — concentric circles, animal tracks, Dreamtime symbols.",
    visualTraits: ["dot patterns", "Dreamtime symbols", "spiritual meaning", "earth tones"],
    commonMotifs: ["concentric circles", "animal tracks", "Dreamtime symbols", "dot patterns"],
    promptKeywords: "Aboriginal Australian inspired tattoo, dot painting aesthetic, concentric circles, Dreamtime symbols, indigenous art, earth tones, spiritual patterns",
    difficulty: "medium",
    popularity: 4,
    colorMode: "black-grey",
    placementFit: ["arm", "back", "shoulder"],
    tool: "Machine",
    toolEmoji: "🪃",
    origin: "Australia",
    culturalSensitive: true,
  },

  // ── HAND-POKE & TRADITIONAL ───────────────────────────────────────────────
  {
    id: "stick_and_poke",
    name: "Stick & Poke",
    category: "Hand-Poke & Traditional",
    description: "Modern hand-poke tattooing — needle dipped in ink, pushed by hand. Softer lines, intimate process, growing in popularity.",
    visualTraits: ["soft lines", "hand-made feel", "intimate process", "minimalist often"],
    commonMotifs: ["simple symbols", "flowers", "animals", "words", "celestial"],
    promptKeywords: "stick and poke tattoo style, hand-poked, soft lines, hand-made aesthetic, minimalist, organic imperfect lines, DIY tattoo art",
    difficulty: "easy",
    popularity: 7,
    colorMode: "black",
    placementFit: ["ankle", "wrist", "finger", "forearm"],
    tool: "Hand Needle",
    toolEmoji: "🪡",
    origin: "Global",
  },
  {
    id: "tebori",
    name: "Tebori (手彫り)",
    category: "Hand-Poke & Traditional",
    description: "Ancient Japanese hand-tattooing technique. Metal or bamboo tool with needles pushed by hand. Creates softer gradients than machines.",
    visualTraits: ["soft gradients", "hand-pushed", "Irezumi style", "unique skin texture"],
    commonMotifs: ["koi fish", "dragons", "cherry blossoms", "waves", "tigers"],
    promptKeywords: "tebori Japanese tattoo style, traditional irezumi, hand-poked with bamboo tool, soft gradients, Japanese traditional art, koi fish dragons cherry blossoms",
    difficulty: "advanced",
    popularity: 6,
    colorMode: "black-grey/full-color",
    placementFit: ["sleeve", "back", "chest", "leg"],
    tool: "Bamboo / Metal Tebori Tool",
    toolEmoji: "🎋",
    origin: "Japan",
    culturalSensitive: true,
  },
  {
    id: "filipino_batok",
    name: "Filipino Batok",
    category: "Hand-Poke & Traditional",
    description: "Ancient Filipino tattooing by the Kalinga tribe. Geometric patterns marking achievements, status and beauty.",
    visualTraits: ["geometric", "achievement marks", "female artists", "tribal patterns"],
    commonMotifs: ["geometric bands", "achievement symbols", "tribal patterns", "nature motifs"],
    promptKeywords: "Filipino batok tattoo style, Kalinga tribal tattoo, geometric patterns, traditional Filipino tattoo art, achievement markings",
    difficulty: "advanced",
    popularity: 4,
    colorMode: "black",
    placementFit: ["arm", "hand", "chest", "face"],
    tool: "Thorn / Citrus Spine",
    toolEmoji: "🌿",
    origin: "Philippines",
    culturalSensitive: true,
  },

  // ── UNDERGROUND & STREET ──────────────────────────────────────────────────
  {
    id: "prison_style",
    name: "Prison / Jail Style",
    category: "Underground & Street",
    description: "Raw, gritty hand-poked tattoos made with improvised tools — needles, staples, guitar strings. Rough lines, deep cultural meaning.",
    visualTraits: ["raw linework", "improvised tools", "gritty aesthetic", "cultural symbolism"],
    commonMotifs: ["teardrops", "spiderwebs", "playing cards", "stars", "barbed wire", "clocks"],
    promptKeywords: "prison tattoo style, raw gritty linework, stick and poke aesthetic, underground tattoo art, rough hand-poked lines, bold simple imagery, jailhouse tattoo",
    difficulty: "easy",
    popularity: 6,
    colorMode: "black",
    placementFit: ["hand", "neck", "face", "knuckles", "forearm"],
    tool: "Makeshift Needle / Pen / Staple",
    toolEmoji: "📎",
    origin: "Global Prison Culture",
  },
  {
    id: "new_school",
    name: "New School",
    category: "Underground & Street",
    description: "Cartoonish, exaggerated proportions, graffiti influence, vivid neon colours and bold outlines.",
    visualTraits: ["cartoon-like", "exaggerated proportions", "neon colours", "graffiti influence"],
    commonMotifs: ["cartoon characters", "graffiti art", "pop culture", "exaggerated animals"],
    promptKeywords: "new school tattoo style, cartoon-like, exaggerated proportions, vivid neon colors, bold outlines, graffiti influence, pop art tattoo",
    difficulty: "advanced",
    popularity: 6,
    colorMode: "full-color",
    placementFit: ["arm", "calf", "back"],
    tool: "Coil Machine",
    toolEmoji: "🎨",
    origin: "USA / UK",
  },
  {
    id: "lettering",
    name: "Script / Lettering",
    category: "Underground & Street",
    description: "Custom typography — Old English, cursive script, calligraphy, graffiti lettering. Words and phrases as art.",
    visualTraits: ["custom typography", "Old English", "cursive script", "calligraphy"],
    commonMotifs: ["names", "quotes", "dates", "words", "phrases"],
    promptKeywords: "tattoo lettering style, custom typography, Old English script, cursive calligraphy, elegant lettering, tattoo font design",
    difficulty: "medium",
    popularity: 9,
    colorMode: "black",
    placementFit: ["forearm", "ribs", "collarbone", "back", "knuckles"],
    tool: "Coil / Rotary Machine",
    toolEmoji: "✍️",
    origin: "Global",
    featured: true,
  },
];

export const MOOD_FILTERS = [
  "Bold", "Dark", "Elegant", "Spiritual", "Futuristic",
  "Minimal", "Feminine", "Masculine", "Aggressive", "Soft",
  "Mystical", "Luxury", "Playful", "Sacred", "Raw",
];

export const SUBJECT_FILTERS = [
  "Floral", "Animals", "Skulls", "Mythology", "Religious",
  "Symbols", "Lettering", "Anime", "Nature", "Abstract",
  "Weapons", "Celestial", "Portraits", "Geometric", "Marine",
];

export const COLOR_MODE_FILTERS = [
  "Black Only", "Black & Grey", "Full Colour",
];

export function getStyleById(id: string): TattooStyle | undefined {
  return TATTOO_STYLES.find((s) => s.id === id);
}

export function getStylesByCategory(category: TattooCategory): TattooStyle[] {
  return TATTOO_STYLES.filter((s) => s.category === category);
}

export function getFeaturedStyles(): TattooStyle[] {
  return TATTOO_STYLES.filter((s) => s.featured);
}

export function getStylePromptKeywords(id: string): string {
  return getStyleById(id)?.promptKeywords || "";
}
